server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: false
spring:
  datasource:
    dbcp2:
      max-total: ${DATASOURCE_MAX_ACTIVE}
    hikari:
      maximum-pool-size: ${DATASOURCE_MAX_ACTIVE}
    tomcat:
      max-active: ${DATASOURCE_MAX_ACTIVE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: jdbc:mysql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_NAME}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          time_zone: America/Sao_Paulo
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: null
    password: null
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
