server:
  port: ${PORT}
  servlet:
    session:
      cookie:
        secure: ${SESSION_COOKIE_SECURE_FLAG}
spring:
  datasource:
    dbcp2:
      max-total: ${DATASOURCE_MAX_ACTIVE}
    hikari:
      maximum-pool-size: ${DATASOURCE_MAX_ACTIVE}
    tomcat:
      max-active: ${DATASOURCE_MAX_ACTIVE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: jdbc:mysql://${DATASOURCE_HOST}:${DATASOURCE_PORT}/${DATASOURCE_NAME}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          time_zone: ${SPRING_JPA_TIMEZONE}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH}
          starttls:
            enable: ${MAIL_TLS}
  main:
    allow-circular-references: true