server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        secure: ${SESSION_COOKIE_SECURE_FLAG:false}
spring:
  datasource:
    dbcp2:
      max-total: ${DATASOURCE_MAX_ACTIVE:10}
    hikari:
      maximum-pool-size: ${DATASOURCE_MAX_ACTIVE:10}
    tomcat:
      max-active: ${DATASOURCE_MAX_ACTIVE:10}
    username: ${DATASOURCE_USERNAME:condominio}
    password: ${DATASOURCE_PASSWORD:secret}
    url: jdbc:mysql://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/${DATASOURCE_NAME:condominio}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          time_zone: ${SPRING_JPA_TIMEZONE:America/Sao_Paulo}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    username: ${MAIL_USERNAME:null}
    password: ${MAIL_PASSWORD:null}
    port: ${MAIL_PORT:587}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH:true}
          starttls:
            enable: ${MAIL_TLS:true}
