server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        secure: ${SESSION_COOKIE_SECURE_FLAG:false}
spring:
  datasource:
    dbcp2:
      max-total: ${SPRING_DATASOURCE_MAX_ACTIVE:10}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_MAX_ACTIVE:10}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    tomcat:
      max-active: ${SPRING_DATASOURCE_MAX_ACTIVE:10}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/condominio?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          time_zone: ${SPRING_JPA_TIMEZONE:America/Sao_Paulo}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    password: ${MAIL_PASSWORD:palm2condo}
    port: ${MAIL_PORT:587}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH:true}
          starttls:
            enable: ${MAIL_TLS:true}
    username: ${MAIL_USERNAME:condominiopalmeirasdois}
